//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace KeysProject.Models
{
    
    [MetadataType(typeof(ProductMetadata))]
    public partial class Product
    {
        public Product()
        {
            this.ProductSolds = new HashSet<ProductSold>();
        }

        [Required]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Id is not valid.")]
        public int Id { get; set; }
        [Required]
        [RegularExpression("^[a-zA-Z]*$", ErrorMessage = "Name can only contain letters.")]
        [StringLength(10, MinimumLength = 3, ErrorMessage = "Name should be between 3 and 10 letters")]
        public string Name { get; set; }
        [Required]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Price must be a number")]
        [MaxLength(3, ErrorMessage = "The price cannot be longer than 3 digits.")]
        [Range(1, 999, ErrorMessage = "Price must range from 1 to 999.")]
        public string Price { get; set; }
    
        public virtual ICollection<ProductSold> ProductSolds { get; set; }
    }
}
